/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package apphandicaped;

import apphandicaped.UI.AWTInterface;
import apphandicaped.UI.RegisterInterface;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }


    public static void main(String[] args) {
        RegisterInterface.main(null);
    }
}