/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package apphandicaped;

import apphandicaped.UI.AWTInterface;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }


    public static void main(String[] args) {
        AWTInterface UI = new AWTInterface();
        System.out.println(new App().getGreeting());
    }
}