
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package apphandicaped.DB;

import org.junit.Test;
import static org.junit.Assert.*;

public class controllerTest {
    @Test 
    public void ReadTabletest() {
        assertEquals("should be equal", 1, 2-1, 3);
        
    }
}
